### ISSUE TITLE
Unable to find how to configure autoprefixer-rails when used with jekyll-assets

### ISSUE THREAD

**Issue by nhoizey** [ai/autoprefixer-rails#100]
As suggested in [Jekyll Assets](https://github.com/jekyll/jekyll-assets) documentation, I installed the `autoprefixer-rails` gem, and my CSS is indeed modified by Autoprefixer with a few vendor prefixes added to it.

But I can't find how to configure which browsers I want to support.

I've tried several file names:
- `_autoprefixer.yml`
- `autoprefixer.yml`
- `browserslist`

Any hint?

I have also open an issue on Jekyll Assets: https://github.com/jekyll/jekyll-assets/issues/314

**Comment by ai** [comment]
You need to use `browserslist` config. If should be in any folder in file path.

If it didn’t work, please try to debug this part of file (sorry, I didn’t use Jekyll): https://github.com/ai/autoprefixer-rails/blob/master/lib/autoprefixer-rails/processor.rb#L92-L102

**Comment by nhoizey** [comment]
I tried to add a `puts` in here, but nothing showed up in the console when I ran `jekyll build`…

I have to first be sure `autoprefixer-rails` is used.

**Comment by nhoizey** [comment]
What about this, where `autoprefixer.yml` seems to be the config file?

**Comment by ai** [comment]
`autoprefixer.yml` is Rails config only, I didn’t test it with Sprockets usage.

**Comment by nhoizey** [comment]
Ok, thanks.

I'll continue looking for help on the Jekyll Assets side…

**Comment by nhoizey** [comment]
Here is the solution:
https://github.com/jekyll/jekyll-assets/issues/314#issuecomment-237675756
