### ISSUE TITLE
Rails 5 support?

### ISSUE THREAD

**Issue by caseybaggz** [ai/autoprefixer-rails#104]
Any update on if you are supporting Rails 5 yet? Getting sprockets deprecation errors when running the server. Great gem!

**Comment by ai** [comment]
Did you update to latest 6.4.0.1?

If yes, please show warning message.

**Comment by caseybaggz** [comment]
Oh, yeah...good idea. That worked! Now using `gem "autoprefixer-rails", ">= 6.4.0.1"` for Rails 5.
