### ISSUE TITLE
iPad ios8 Safari bugs found when using Flexbox

### ISSUE THREAD

**Issue by puerh** [ai/autoprefixer-rails#107]
If there's any 'justify-content: space-around' in the stylesheets file,
autoprefixer-rails do nothing for ipad ios8 safari.
It will also break all components that used flexbox in the web page.

Solution
Use '-webkit-justify-content: space-around'

**Comment by ai** [comment]
This Safari version is not in default browsers `> 1%, last 2 versions, Firefox ESR`. Set browsers manually.
