### ISSUE TITLE
Order of appearance of prefixed properties?

### ISSUE THREAD

**Issue by marvindanig** [ai/autoprefixer-rails#109]
So on my rails 5 app, I have a `_reusable.scss` containing a class rule like so:

```

.flex {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    justify-content: center;
}

```

After post processing vendor prefixes, `autoprefixer-rails` spits out the following class rule:

```
.flex {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center;
    -webkit-box-pack: center;
    -ms-flex-pack: center;
    justify-content: center;
}

```

Now my chrome canary (Version 54.0.2840.0 canary (64-bit)) interprets `display:-webkit-box;` on line 1 correctly but that is soon overwritten by the rule at line no 3 `display: flex;` (which canary doesn't support at the moment) and thus the site design falls apart. 

A simple fix here would to swap lines for `display:flex;` and `display:-webkit-box;`.  Is this something that can be easily done on `autoprefixer-rails`?

To test visit homepage: [https://bubbl.in](https://bubbl.in) on stable chrome and the following is a screenshot on chrome canary where `.flex` isn't effectively applied:

[ [screenshot](http://imgur.com/FP8DL7L) ]

**Comment by ai** [comment]
1. Wrong repo. This repo is for Rails wrapper on top of Autoprefixer. Of course, this issue could not be part of wrapper, but is in core.
2. Canary [supports](http://caniuse.com/#search=flexbox) `display: flex`. According CSS rules, browsers could not accept declaration if it doesn’t understand it. So Chrome takes `display: flex` and overrides `-webkit-box` only because it understand `flex`.

**Comment by ai** [comment]
You should check your flexbox styles. Old webkit supports different spec. So when you use `display: -webkit-box` it enables old flexbox engine. Maybe you have a issue in flexbox, but old spec is more tolerant for it.

**Comment by marvindanig** [comment]
> So when you use display: -webkit-box it enables old flexbox engine. Maybe you have a issue in flexbox, but old spec is more tolerant for it.

I didn't use `display: -webkit-box` anywhere on my *.scss declarations. I have only this much on my `*.scss` file:

```
.flex {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    justify-content: center;
}

```

It is the output from the autoprefixer that uses `display: -webkit-box`! 

Thank you for the hint that something is using an "old flexbox engine", so I looked at the gemspec: `autoprefixer-rails (6.4.0.3)`, which seems to be the latest. 

Digging. Will update this note shortly.

**Comment by ai** [comment]
Yeap, Autoprefixer adds prefix. But I told you about Flexbox engine in browsers.

But Chrome doesn't need prefix. So it is not problem with order.

**Comment by marvindanig** [comment]
hmm, it is something about chrome canary then. :(
