### ISSUE TITLE
Issue with transform on Safari for iPad 

### ISSUE THREAD

**Issue by wouter-muller** [ai/autoprefixer-rails#110]
First of all, i LOVE autoprefixer-rails. It has helped me in my projects immensely.

Having said that, I've ran into the issue where CSS like this:
```
transform: translateY(-50%);
```
...wasn't doing anything on Safari for iPad. After some research i discovered it still needs the webkit browser prefix. I added that manually and it worked. 

How come autoprefixer doesn't add this prefix by itself? Safari for iPad is a major browser so i am assuming it is included by default and i don't have to add it to the `browserslist`.

**Comment by wouter-muller** [comment]
Caniuse.com doesn't list this issue either, so could very well be that the problem is on their end...

**Comment by ai** [comment]
What Safari version you have on iPad? Maybe you have old iPad without Safari updates, so you have Safari 8?

It is not the latest Safari, and it is not really popular (not match in default `> 1%` browser requirement). So you need to set manually in `browserslist`.

**Comment by wouter-muller** [comment]
This iPad was running the latest version of iOS...
