### ISSUE TITLE
Heroku not picking up config settings

### ISSUE THREAD

**Issue by lorenzsell** [ai/autoprefixer-rails#111]
I'm deploying to Heroku and having issues with Heroku not picking up settings in my config/autoprefixer.yml file.  When I precompile the assets locally, it works.  But when the assets are compiled during slug compilation, only the default autoprefixer settings are in effect.

Am I missing something here?

**Comment by ai** [comment]
Sorry, have no idea :).

I have no big experience with Heroku.

**Comment by lorenzsell** [comment]
Do you have any suggestions?  I've set up my browserlist config file in app/browserlist and have the following lines in it:

IE >= 10
Safari >= 6

When I precompile locally and push to heroku, everything works.  When compilation is done as part of the push to heroku instead, autoprefixer defaults to its default settings.  I've spent hours trying to debug this and have no idea how to have autoprefixer pick up the proper settings.  Anything else I can try?

Thank you.

**Comment by ai** [comment]
Have no idea :). Ask Heroku support.

**Comment by lorenzsell** [comment]
Here's the response I got from Heroku which fixed the problem:

> This could be a caching issue during slug compilation. Assets are only compiled if the source file has changed, otherwise sprockets will reuse the previously compiled files. To rule this out, can you purge the dyno cache by installing https://github.com/heroku/heroku-repo and running heroku repo:purge_cache -a appname, then redeploy your application with assets set to precompile.

**Comment by marlonmantilla** [comment]
Hi @lorenzsell, I'm having the exact same issue but didn't worked your steps I tried heroku-repo and then compiling assets with `heroku run rake assets:precompile` ... maybe I'm missing something.

**Comment by marlonmantilla** [comment]
I make it work with this approach https://github.com/ai/autoprefixer-rails/issues/26, bumping `config.assets.version` in config/application.rb.
