### ISSUE TITLE
Specify different configs per environment?

### ISSUE THREAD

**Issue by danethomas** [ai/autoprefixer-rails#114]
Is it possible to specify different configs for different environments?

I've tried using browserl.ists env config's but they don't seem to work. Could just be a syntax issue though. 

We need to include webkit prefix's for some capybara-webkit flexbox support but have no need for it in production.

**Comment by ai** [comment]
What `browserslist` do you have?

**Comment by ai** [comment]
In error report always explain what you did, what expected result and what real result.

**Comment by danethomas** [comment]
I'm not sure specifically what browserlist I'm using - I'm now using `v6.7.2` of `autoprefixer-rails`

I guess it was more of a question of how be to do the configuration?

I've playued around with this some more and for my `autoprefixer.yml` I now have:

```
flexbox: no-2009
browsers:
  - "> 1%"
  - "last 2 versions"
  - "IE > 8"
env:
  - "development"
  - "production"
```

I *think* this may be working but I need to do some more testing. 

I've tried putting a `browserlist` file in `app/assets/stylesheets/` but that doesn't seem to do anything. And that syntax isn't compatible with the yaml config. 

```
[production]
last 2 version
ie 9

[development]
last 1 version
```

**Comment by ai** [comment]
```
env: production
```

not a array :)

**Comment by ai** [comment]
I didn’t recommend to use `env` in your case, just use

```
last 2 version
ie 9
```

for all cases.

**Comment by yjukaku** [comment]
I'm also having trouble with this feature.

I want the `config/autoprefixer.yml` file to only effect our test environment, but it doesn't seem to work.

```ruby
# test.rb
yaml = <<YML
env: test
browsers:
  - "> 1%"
  - "last 2 versions"
  - "Chrome > 20"
YML
puts AutoprefixerRails.process('display: flex;', YAML.load(yaml).symbolize_keys)
```

```
bundle exec rails runner -e development test.rb
```

Expected:
`display: -webkit-box;display: -ms-flexbox;display: flex;`

Actual: 
`display: -webkit-box;display: -webkit-flex;display: -ms-flexbox;display: flex;`

Summary: 
Setting `env: test` in the `config/autoprefixer.yml` file doesn't seem to do anything.

**Comment by ai** [comment]
@yjukaku how `env: test` is related to expected output? `env` is used to choose different browsers from `browserslist` config.

```
[production]
last 2 version
ie 9

[development]
last 1 version
```

In you example you define browsers in `browsers` option, so `env` is meanless here.

**Comment by ai** [comment]
Yeap. It is about `browserslist` config.
