### ISSUE TITLE
Can i specify the working directory?

### ISSUE THREAD

**Issue by hr1992** [ai/autoprefixer-rails#115]
Hi!
I add this gem into my project, but `bootstrap-sass` has a lot of warnings.Such as:

```
Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.
```

I just want autoprefixer to work on my `assets` folder.

Is there any other way to do that?

**Comment by ai** [comment]
It is very dangerous warning. You CSS could be broken because of library. So you should force library to fix problem.

**Comment by ai** [comment]
Or move to other library.
