### ISSUE TITLE
`autoprefixer.js` file no longer contains embedded data from the Can I Use

### ISSUE THREAD

**Issue by Taritsyn** [ai/autoprefixer-rails#119]
Due to lack of embedded data from the Can I Use database now there is no possibility to use `autoprefixer.js` file in browser.

**Comment by ai** [comment]
It contains `caniuse-lite` database. It compressed in better way, but still have all data.

What exactly problem do you have?

**Comment by Taritsyn** [comment]
I apologize, did not immediately realize that the data was compressed.
