### ISSUE TITLE
Missing -webkit-flex

### ISSUE THREAD

**Issue by Mathieu-C** [ai/autoprefixer-rails#121]
After some checks my application needs the `-webkit-flex` prefixes to display properly on older iPhones, problem is my code:

    .header-content {
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
Compiles into:

    .header-content {
        display: -webkit-box;
        display: flex;
        -webkit-box-pack: justify;
        justify-content: space-between;
        -webkit-box-align: center;
        align-items: center;
    }
I've tried to set the `config/autoprefixer.yml` up but I can't find the right configuration to get `-webkit-flex` added to the prefixes.

**Comment by ai** [comment]
Check that browsers selected in `browserslst` (or default set if you didn’t change it) really needs this prefix right now.
