### ISSUE TITLE
v7.2.0 causing bootstrap v4.0.0.alpha6 to fail stylesheet link

### ISSUE THREAD

**Issue by xsresearch** [ai/autoprefixer-rails#128]
Using v7.2.0 seems to break compatibility with bootstrap v4.0.0.alpha6 on Rails 5.1.4

>  Showing /usr/src/app/app/views/layouts/application.html.erb where line 7 raised:
> TypeError: Object progress-bar-stripes,1s,linear,infinite has no method 'find'

Line 7 in application.html.erb was:

> <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

application.scss contains only 1 line:

> @<span></span>import "bootstrap";

v7.1.3 was working fine, and v7.1.6 was also tested as working fine.

See attached [Gemfile.lock.txt](https://github.com/ai/autoprefixer-rails/files/1525362/Gemfile.lock.txt) for example Rails 5.1.4 Gemfile.lock for which the issue was observed.

@ai Let me know if further details required to reproduce.

**Comment by ai** [comment]
Can you try to build assets and give me full stack trace.

Also, what Node.js runtime do you use?

**Comment by ai** [comment]
Fixed https://github.com/postcss/autoprefixer/commit/b8cbd673b81360214c3bb4d597b83639aca0027f

**Comment by xsresearch** [comment]
Confirmed resolved.
@ai Thanks!

**Comment by ai** [comment]
Released in 7.2.1
