### ISSUE TITLE
How to disable autoprefixer on test env

### ISSUE THREAD

**Issue by joaovitoras** [ai/autoprefixer-rails#132]
I tried this but it did not work

```ruby
# config/test.rb
Rails.application.configure do
  config.after_initialize do
    AutoprefixerRails.uninstall(config.assets)
  end
end
```

Autoprefixer runs anyway. I'm doing something wrong?

I tried without `config.after_initialize`, but it did not work too.

**Comment by ai** [comment]
Use Node.js Autoprefixer. It is faster and more flexible.

We don't really support Autoprefixer Rails right now.

Technically `uninstall` should work. Try to debug Sprockets during this call, maybe you call `uninstall` in wrong moment?

**Comment by zokioki** [comment]
@joaovitoras If you inspect the assets object in that `#after_initialize` block, you should see that it's an instance of `Sprockets::Railtie::OrderedOptions`. Since uninstall expects an instance of `Sprockets::Environment` you should be able to run the following:

```ruby
Rails.application.configure do
  config.after_initialize do
    AutoprefixerRails.uninstall(Rails.application.assets)
  end
end
```

**Comment by beporter** [comment]
I don't think this has anything to do with initialization _order_. The way Autoprefixer-rails is written, it will **always** try to engage ExecJS before your attempt to disable it. So if your system or docker container lacks a JS runtime, you will always see an error like the following that references ExecJS but is really Autoprefixer's doing (in my case via the [bootstrap gem](https://rubygems.org/gems/bootstrap/versions/4.0.0)):

```
$ bundle exec rails db:schema:load
rails aborted!
ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
/builds/my_project/vendor/ruby/ruby/2.5.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect'
/builds/my_project/vendor/ruby/ruby/2.5.0/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
/builds/my_project/vendor/ruby/ruby/2.5.0/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
/builds/my_project/vendor/ruby/ruby/2.5.0/gems/autoprefixer-rails-10.2.4.0/lib/autoprefixer-rails/processor.rb:4:in `require'
/builds/my_project/vendor/ruby/ruby/2.5.0/gems/autoprefixer-rails-10.2.4.0/lib/autoprefixer-rails/processor.rb:4:in `<top (required)>'
/builds/my_project/vendor/ruby/ruby/2.5.0/gems/autoprefixer-rails-10.2.4.0/lib/autoprefixer-rails.rb:39:in `require_relative'
/builds/my_project/vendor/ruby/ruby/2.5.0/gems/autoprefixer-rails-10.2.4.0/lib/autoprefixer-rails.rb:39:in `<top (required)>'
/builds/my_project/vendor/ruby/ruby/2.5.0/gems/bootstrap-4.3.1/lib/bootstrap/engine.rb:3:in `require'
/builds/my_project/vendor/ruby/ruby/2.5.0/gems/bootstrap-4.3.1/lib/bootstrap/engine.rb:3:in `<top (required)>'
/builds/my_project/vendor/ruby/ruby/2.5.0/gems/bootstrap-4.3.1/lib/bootstrap.rb:61:in `require'
/builds/my_project/vendor/ruby/ruby/2.5.0/gems/bootstrap-4.3.1/lib/bootstrap.rb:61:in `register_rails_engine'
/builds/my_project/vendor/ruby/ruby/2.5.0/gems/bootstrap-4.3.1/lib/bootstrap.rb:11:in `load!'
/builds/my_project/vendor/ruby/ruby/2.5.0/gems/bootstrap-4.3.1/lib/bootstrap.rb:75:in `<top (required)>'
/builds/my_project/config/application.rb:7:in `<top (required)>'
/builds/my_project/Rakefile:4:in `require_relative'
/builds/my_project/Rakefile:4:in `<top (required)>'
/builds/my_project/vendor/ruby/ruby/2.5.0/gems/railties-5.2.5/lib/rails/commands/rake/rake_command.rb:22:in `block in perform'
/builds/my_project/vendor/ruby/ruby/2.5.0/gems/railties-5.2.5/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/builds/my_project/vendor/ruby/ruby/2.5.0/gems/railties-5.2.5/lib/rails/command.rb:48:in `invoke'
/builds/my_project/vendor/ruby/ruby/2.5.0/gems/railties-5.2.5/lib/rails/commands.rb:18:in `<top (required)>'
/builds/my_project/bin/rails:9:in `require'
/builds/my_project/bin/rails:9:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
(See full trace by running task with --trace)
```

This is from our CI build, which shouldn't require anything Node or Javascript related in order to run `rspec`.

**Comment by albb0920** [comment]
Why `execjs` wants to throw error that early is beyond me, but I think you can exclude `autoprefixer-rails` form test group in your Gemfile.

**Comment by beporter** [comment]
Yes that's probably a great alternative if you're using autoprefixer directly, but as I mentioned it's a sub-dependency of (at least) the bootstrap gem as well. 

Depending on your app and test suite, you might get failures from your rails controller actions if you exclude bootstrap from the test group in your Gemfile.

**Comment by albb0920** [comment]
Ahh, I see...

Can you try running with environment variable `EXECJS_RUNTIME=Disabled`?
This should disable execjs.
