### ISSUE TITLE
9.0 Triggering ActionView::Template Error

### ISSUE THREAD

**Issue by noelrappin** [ai/autoprefixer-rails#137]
Rails 5.2 autoprefixer 9.0

All my Rails Capybara tests that try to run with a JavaScript driver give me this:

```
Failure/Error: = stylesheet_link_tag "application", media: "screen" unless params[:print]

      ActionView::Template::Error:
        Current ExecJS runtime does't support ES6. Please install latest Node.js.



      # /Users/noel/.gem/ruby/2.5.1/gems/autoprefixer-rails-9.0.0/lib/autoprefixer-rails/processor.rb:149:in `runtime'
```

My system is running the latest node and the latest Sprockets beta, as far as I can tell, so I'm not sure exactly what to upgrade.

**Comment by jankmet** [comment]
Rails 5.1.6 autoprefixer 9.0
I have same error after modifying sass styles
reverting to 8.6.5 solved the issue

**Comment by ai** [comment]
The error is pretty describable.

You use RubyRacer to run JS. It contains very old JS runtime (so it become impossible to safely run Autoprefixer on this old JS runtime).

Replace it to MiniRacer or install the latest Node.js version (so ExecJS will use Node.js)

**Comment by jcoyne** [comment]
We get this error and we do not have `therubyracer` in our bundle.

**Comment by ai** [comment]
@jcoyne what ExecJS runtime do you use?

**Comment by jcoyne** [comment]
@ai I guess I need to retract that remark.  It was in our bundle as a transitive dependency.

**Comment by jankmet** [comment]
thanks @ai, replacing therubyracer with mini_racer did help (updating node.js didn't)

**Comment by ai** [comment]
Maybe we need to change error text. Do you want to send PR?

**Comment by caiotarifa** [comment]
Replace `therubyracer` by `mini_racer` in `Gemfile`:

```
# gem 'therubyracer', platforms: :ruby
gem 'mini_racer', platforms: :ruby
```

And then:

```
$ bundle install
```

**Comment by ai** [comment]
@jankmet @caiotarifa does somebody want to make warning smarter? And show better instructions depends on current ExecJS runtime?

**Comment by caiotarifa** [comment]
I would find it useful, it would save some time for who have the same problem.

Unfortunately I'm a front end, maybe I don't have enough knowledge to help with this..

**Comment by jankmet** [comment]
@ai  I try to look at it, but I can't promise anything, I haven't much experience with  ExecJS runtime...
I would also suggest some kind of post-install message...

**Comment by ai** [comment]
> I haven't much experience with ExecJS runtime

I am too 😄

> I would also suggest some kind of post-install message...

It is easy to miss `post-install` message. Error text is a better place in my opinion.

**Comment by jankmet** [comment]
of course I meant both of them :) relevant Error Message and post-install by bundle update...

**Comment by jankmet** [comment]
@ai  I think some people are waiting for autoprefixer-rails > 9.0 therubyracer fix,
but this this not planned, autoprefixer-rails > 9.0 will not work with therubyracer, correct?

**Comment by ai** [comment]
@jankmet yes, we don't sorry TheRubyRacer.

This project is not supported and V8 there is very old. There is no easy way to support it.

**Comment by ai** [comment]
This issue like only to see more clear error message. You will have it until you will remove `therubyracer`.

**Comment by ai** [comment]
Error message fixed by @jankmet https://github.com/ai/autoprefixer-rails/pull/138

Thanks :+1:

**Comment by DrobyshevAlex** [comment]
I use version 9.1.1 and got error

> therubyracer (V8) runtime does’t support ES6. Please update or replace your current ExecJS runtime.

I can't use mini_racer. Can you help me please?)

**Comment by ai** [comment]
@DrobyshevAlex if you can't use `mini_racer` you should use Node.js as runtime for ExecJS. Sorry, TheRubyRacer just can't run Autoprefixer JS.

**Comment by DrobyshevAlex** [comment]
Thank you very much! It works!

**Comment by ai** [comment]
@DrobyshevAlex I improved error message 7e67590
