### ISSUE TITLE
ExecJS::ProgramError: TypeError: Object #<Object> has no method 'log2'

### ISSUE THREAD

**Issue by brunto** [ai/autoprefixer-rails#139]
When I use autoprefixer-rails 9.0.2 I have the following error on assets precompilation:

```
       rake aborted!
       ExecJS::ProgramError: TypeError: Object #<Object> has no method 'log2'
       unpackSupport ((execjs):14780:36)
       (execjs):14794:28
       Array.reduce (native)
       (execjs):14792:70
       Array.reduce (native)
       unpackFeature ((execjs):14790:44)
       f ((execjs):20:10)
       Object.caniuse-lite ((execjs):88:1)
       o ((execjs):1:913)
       (execjs):1:964
       /vendor/bundle/ruby/2.5.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:39:in `exec'
```

This doesn't appear with previous 8.x version.

**Comment by ai** [comment]
What ExecJS runtime do you use?

**Comment by ai** [comment]
MiniRacer or Node.js version?

**Comment by pscdodd** [comment]
Have the same problem running the Rails 4 application in production mode with version 9.0.2:
F, [2018-08-03T13:16:24.189004 #1302] FATAL -- :
ActionView::Template::Error (TypeError: Object #<Object> has no method 'log2'):
In the version used previously (8.6.3) the issue did not occur.

**Comment by brunto** [comment]
Node.js for me.

**Comment by ai** [comment]
@brunto and everyone else, show me `node --version` output.

**Comment by brunto** [comment]
v8.9.4 for me

**Comment by ai** [comment]
I fixed it in `caniuse-lite` https://github.com/ben-eb/caniuse-lite/commit/baf3f7a825f62226efc27463ee2e05f6e52d3049

I will release it on next `caniuse-db` release

**Comment by pscdodd** [comment]
nodejs --version
v0.10.25

**Comment by ai** [comment]
@pscdodd please update your Node ASAP. You use very old version without security updates.

**Comment by pscdodd** [comment]
nodejs  v0.10.25 is actually the latest version on Ubuntu 14.04 LTS! I installed the latest LTS version (linux binaries 64bit 8.11.3) from https://nodejs.org/en/download/. After prefixing the nodejs path and adding a link from bin/node to bin/nodejs it worked.  Thanks for the help.

**Comment by ai** [comment]
Fixed https://github.com/ben-eb/caniuse-lite/commit/baf3f7a825f62226efc27463ee2e05f6e52d3049

**Comment by ai** [comment]
Released in 9.1.1

**Comment by bennettlumbera** [comment]
I have the same issue as you @pscdodd working with the same nodejs version. I'm not sure what you mean with you prefixed the nodejs path and added a link from bin/node to bin/nodejs.

**Comment by ai** [comment]
@bennettlumbera what Autoprefixer Rails version do you use?

**Comment by bennettlumbera** [comment]
@ai gem 'autoprefixer-rails', '~> 9.0', '>= 9.0.2'

I've had trouble getting bootstrap integrated into my application and this is the first time I've had this issue come up when trying to do that.

**Comment by gino-225** [comment]
@bennettlumbera i also has this issue when using bootstrap, but managed to fix it but cant remember for the life of me how i did it. Now someone has cloned my app and they are having the same issue

**Comment by ai** [comment]
@bennettlumbera look exact version in Gemfile.lock

@gino-225 what Autoprefixer version do you use?

**Comment by gino-225** [comment]
@ai autoprefixer-rails (9.1.0)

**Comment by ai** [comment]
@gino-225 update it. We fixed this issue in next version.

**Comment by gino-225** [comment]
@ai ok thanks. Im new to rails, how would i go about doing this?

**Comment by ai** [comment]
@gino-225 `bundle update autoprefixer-rails`

**Comment by bennettlumbera** [comment]
@ai I have 9.1.3

**Comment by bennettlumbera** [comment]
@ai @gino-225 I ended up adding 

`gem 'mini_racer', platforms: :ruby` 

to Gemfile and seemed to work. I found the solution here: https://github.com/ai/autoprefixer-rails/issues/137#issuecomment-406329798

**Comment by ai** [comment]
@bennettlumbera very strange. There is no `log2` function in Autoprefixer Rails 9.1.3 anymore https://raw.githubusercontent.com/ai/autoprefixer-rails/master/vendor/autoprefixer.js

**Comment by dnwilson** [comment]
Having the same issue with 9.1.3 trying @bennettlumbera's solution
