### ISSUE TITLE
Autoprefixer is not able to find Node v6.11.1

### ISSUE THREAD

**Issue by zedalaye** [ai/autoprefixer-rails#143]
When I deploy my app to Scalingo using `git push`, I get this error: 

````
       ...
       Bundle complete! 84 Gemfile dependencies, 202 gems now installed.
       Gems in the groups development and test were not installed.
       Bundled gems are installed into ./vendor/bundle.
       Post-install message from attr_encrypted:
       WARNING: Several insecure default options and features were deprecated in attr_encrypted v2.0.0.
       Additionally, there was a bug in Encryptor v2.0.0 that insecurely encrypted data when using an AES-*-GCM algorithm.
       This bug was fixed but introduced breaking changes between v2.x and v3.x.
       Please see the README for more information regarding upgrading to attr_encrypted v3.0.0.
       Bundle completed (10.55s)
       Cleaning up the bundler cache.
       Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.16.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
       Removing pghero (2.1.1)
       Removing autoprefixer-rails (8.6.5)
       Removing slim (4.0.0)
-----> Installing node-v6.11.1-linux-x64
-----> Detecting rake tasks
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       Yarn executable was not detected in the system.
       Download Yarn at https://yarnpkg.com/en/docs/install
       rake aborted!
       Autoprefixer doesn’t support Node v0.10.25. Update it.
 !   Error deploying the application
       /build/8dd03aff-47b4-4d40-a0b7-a576ceb117d9/vendor/bundle/ruby/2.5.0/gems/autoprefixer-rails-9.1.3/lib/autoprefixer-rails/processor.rb:163:in `runtime'
 !   → Invalid return code from buildpack 
       /build/8dd03aff-47b4-4d40-a0b7-a576ceb117d9/vendor/bundle/ruby/2.5.0/gems/autoprefixer-rails-9.1.3/lib/autoprefixer-rails/processor.rb:37:in `process'
 emote: 
       /build/8dd03aff-47b4-4d40-a0b7-a576ceb117d9/vendor/bundle/ruby/2.5.0/gems/autoprefixer-rails-9.1.3/lib/autoprefixer-rails/sprockets.rb:20:in `run'
````

That not happens with AutoPrefixer < 9 (8.6.5)

**Comment by ai** [comment]
> That not happens with AutoPrefixer < 9 (8.6.5)

It was because 8.x supported Node.js 0.10.

> When I deploy my app to Scalingo using git push, I get this error:

You need to write to Scalingo support about the way how they install Node.js version

**Comment by Soulou** [comment]
@ai Scalingo CTO here,

Node 6.1.11 is installed in this environment, it's the version returned by 'node --version' in this case.

The thing is that a system executable named nodejs from the Ubuntu package is also installed by default and it seems autoprefixer is looking at this executable first which is obsolete and not the 'node' binary.

Is there such priority list?

**Comment by ai** [comment]
@Soulou wow, great support for your customers :D 

The main problem is that AutoprefixerRails just uses ExecJS to run JS code in Ruby.

1. Here is how ExecJS creates Node,js environment https://github.com/rails/execjs/blob/master/lib/execjs/runtimes.rb#L21-L26
2. Here is the external runtime https://github.com/rails/execjs/blob/master/lib/execjs/external_runtime.rb

Seems like the problem is because `nodejs` is 0.10 and `node` is 6.x. And ExecJS try to use `nodejs` first.

Solutions:

1. Ask to ExecJS to change Node.js runtime. But I don’t think they will agree with breaking changes.
2. Change virtual machines in Scalingo to have `nodejs` as a symlink to `node`. But it doesn’t look like the simplest way.

If you have any another idea, I am open.

**Comment by Soulou** [comment]
Hi @ai, we've already started implementing 2. So it will be sorted out.

I can't see any other solution here. In long term we'll see what to do with the default stack nodejs ubuntu package, we don't want to have a breaking change here either. So the solution is to add the symlink when a custom version of node is added.

Thanks for your message, we've now all what we need to handle this.

**Comment by bobmaerten** [comment]
Just to say Scalingo resolved this problem in their PaaS a few days ago and we successfully deployed a app using this gem.
