### ISSUE TITLE
test/support different runtimes

### ISSUE THREAD

**Issue by eloyesp** [ai/autoprefixer-rails#146]
Currently tests are run with node.js only, it would be great to make sure tests are run with other runtimes, to make sure they are supported.

On the other hand, if there are specific requirements on the runtime that should be used, it could help a lot have that explicit in the README.

For what I read in [the code][1] it seems that nodejs version should be `>= 6.0` and `therubyracer` is not supported. I where testing with [duktape][2] and it seems it does not work either.

 [1]: https://github.com/ai/autoprefixer-rails/blob/14d53730ca67ac8af33235905ee45488cfb54760/lib/autoprefixer-rails/processor.rb#L163
 [2]: https://github.com/judofyr/duktape.rb

**Comment by ai** [comment]
> Currently tests are run with node.js only, it would be great to make sure tests are run with other runtimes, to make sure they are supported.

Are you sure? I have specific line on Travis CI config to run it on `miniracer` https://github.com/ai/autoprefixer-rails/blob/master/.travis.yml#L11-L14

> For what I read in the code it seems that nodejs version should be >= 6.0 and therubyracer is not supported.

Yeap, `therubyracer` project is dead for a long time ago.

**Comment by eloyesp** [comment]
> Are you sure? I have specific line on Travis CI config to run it on miniracer https://github.com/ai/autoprefixer-rails/blob/master/.travis.yml#L11-L14

You are right, I didn't understood the comment there, the downside of making it that way is that it will fallback to node if miniracer is not available. Using `EXECJS_RUNTIME=MiniRacer` would prevent that and also add readability.

Any thought about `duktape`, it is higher on the runtimes array on execjs, so it should be better.

Thanks for your response.

**Comment by ai** [comment]
> Using EXECJS_RUNTIME=MiniRacer would prevent that and also add readability.

Good idea. Do you want to send PR to save your name in the project history?

> Any thought about duktape, it is higher on the runtimes array on execjs, so it should be better.

It is the first when I hear about duktape. It is JS runtime like miniracer? Yeap, let’s add it to the test (but I am not sure, will I support it, if it will have a lot of problems)

**Comment by eloyesp** [comment]
@ai Feel free to add this commit that add information on the README https://github.com/eloyesp/autoprefixer-rails/commit/b699bbfdea96470fd40872bd58cda5634d6274eb
