### ISSUE TITLE
Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`

### ISSUE THREAD

**Issue by pelcasandra** [ai/autoprefixer-rails#161]
I'm getting the following message 

```
Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.
```

I'm using this declaration in the code. 

```css
background: linear-gradient(90deg, #2ec3eb, #f434bc);
```

And the output is becoming:

```css
  background: -webkit-gradient(linear, left top, right top, from(#2ec3eb), to(#f434bc));
  background: linear-gradient(90deg, #2ec3eb, #f434bc);
```

It isn't clear from the message what is wrong and what needs to be changed. I'm not using `right` as the message suggests but rather `90deg`. 

Is there any workaround to make this work?

**Comment by ai** [comment]
I tried the same CSS and did’t get any warnings

```js
let autoprefixer = require('./')

let result = autoprefixer
  .process('a{background: linear-gradient(90deg, #2ec3eb, #f434bc);}')

console.log(result.messages) //=> []
```

Maybe warning came from Autoprefixer from different CSS tools. Sorry, I can’t help with the environment.

If you find a way to reproduce it, feel free to reopen an issue.
