### ISSUE TITLE
Using RuboCop?

### ISSUE THREAD

**Issue by utkarsh2102** [ai/autoprefixer-rails#164]
Hi @ai,

Thanks for working on and maintaining this amazing library! :rocket: 
However, since we maintain this in Debian and if I run `rubocop` on the source tree, I get a lot of offenses. Therefore, I'd ask, would you be open to using RuboCop?I'll be happy to raise a PR if so? :smile:

**Comment by ai** [comment]
Yeap, let's try

**Comment by utkarsh2102** [comment]
Perfect, I'll get around to doing it by this weekend!

Thank you very much! :fire::100:

**Comment by olleolleolle** [comment]
@utkarsh2102 Can this be closed, now that #166 is merged?

**Comment by utkarsh2102** [comment]
Absolutely!
