### ISSUE TITLE
How to use custom browser stats for Rails?

### ISSUE THREAD

**Issue by joker-777** [ai/autoprefixer-rails#165]
Hi,

I have a json file `browserslist-stats.json` with our custom browser stats and would like to use it with `autoprefixer`. I can see that there is a `stats` option but how can it be used in Rails where it only uses the `config/autoprefixer.yaml` file for this config?

**Comment by ai** [comment]
Autoprefixer Rails doesn’t support this feature.

We are thinking of deprecating Autoprefixer Rails. So we recommend switching to `webpacker` with `postcss-loader` and `autoprefixer` as a plugin to PostCSS.

**Comment by joker-777** [comment]
Yes, we already use `webpacker` but for now only for our javascript. We still use the asset pipeline for our css and we won't change it soon.

It would be already enough if I could initialize `autoprefixer-rails` manually in `config/initializers` and not let it install automatically.

**Comment by joker-777** [comment]
BTW, thanks a lot for your quick answer. Amazing!

**Comment by ai** [comment]
> Yes, we already use webpacker but for now only for our javascript. We still use the asset pipeline for our css and we won't change it soon.

Unfortunately, it is hard to read files from the JS code of Autoprefixer, and copying `browserslist-stats.json` finding code to Ruby will decrease maintainability (we still have [not enough funds](https://opencollective.com/postcss/) to do proper support).

This thing could be another reason to move CSS to a webpack too.
