### ISSUE TITLE
With latest autoprefixer-rails-9.8.6.4 ExecJS::RuntimeError

### ISSUE THREAD

**Issue by aboltart** [ai/autoprefixer-rails#178]
ExecJS::RuntimeError: /tmp/execjs20200915-1198-lchlf9js:741
        defaults = { ...defaults, value: String(defaults.value) };
                     ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
(execjs):741
/intermediate_gems/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:207:in `exec_runtime'
/intermediate_gems/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:39:in `exec'
/intermediate_gems/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:14:in `initialize'
/intermediate_gems/gems/execjs-2.7.0/lib/execjs/runtime.rb:57:in `compile'
/intermediate_gems/gems/execjs-2.7.0/lib/execjs/module.rb:27:in `compile'
/intermediate_gems/gems/autoprefixer-rails-9.8.6.4/lib/autoprefixer-rails/processor.rb:148:in `runtime'
/intermediate_gems/gems/autoprefixer-rails-9.8.6.4/lib/autoprefixer-rails/processor.rb:33:in `process'
/intermediate_gems/gems/autoprefixer-rails-9.8.6.4/lib/autoprefixer-rails/sprockets.rb:22:in `run'
/intermediate_gems/gems/autoprefixer-rails-9.8.6.4/lib/autoprefixer-rails/sprockets.rb:16:in `call'

**Comment by ai** [comment]
@albb0920 did I released Autoprefixer 10 pre-release in 9.8.6.4? :(

**Comment by ai** [comment]
@albb0920 here is what plan do I see:

1. You send PR to revert `autoprefixer.js` changes so we will use old Autoprefixer for 9.8.6.5 to hide the warning for the 9.x branch.
2. I will release 9.8.6.5.
3. You will update `autoprefixer.js` in another PR (with fixes for @aboltart issue)
4. I will release it as 10.0.

**Comment by mattalat** [comment]
@ai Yes, it looks like you may have! I am seeing similar warnings on some of my builds. Reverting to `9.8.6.3` fixed things.

Also, I believe that Node 6 may be unsupported on this update (what was intended to be 10.x). I have not tested this thoroughly but wanted to point it out.

Thanks for all your hard work.

**Comment by ai** [comment]
Yeap, hotfix is to update Node.js to 12 (Node.js 6 has no security updates anymore)

**Comment by ai** [comment]
OK. I temporarily reverted `autoprefixer.js` changes and released the old version in `9.8.6.5`.

Then I bring `autoprefixer.js` back so @albb0920 will be able to continue his work on Autoprefixer Rails 10.

**Comment by albb0920** [comment]
Sorry, I should make this more clear. I did mention my PRs are based on master branch / development version of autoprefixer, and we might need a 9.x branch. I thought you think 10.x is stable enough when I se you release 😰

I didn’t target the released version for several reasons. One of them is 9.x distributes babel transpiled script, IIRC autoprefixer 10 won’t be transpiled.

**Comment by ai** [comment]
@albb0920 it was my mistake of not creating `10.x` branch 😅

Now I created `v9.x` branch if we will need to send patches to 9.x users.

**Comment by albb0920** [comment]
So for 9.x, do you want a PR to rmove deprecation warning? (or maybe you can just cherry-pick 9306d3ed5ad034dff1d293ce3b73d3f9df85af70 )

For 10.x, I think this issue here is we need to check whether the runtime supports the feature set we need. (Or we could just check Node / mini_racer version, as that's the only two runtime we test against.)

**Comment by ai** [comment]
> So for 9.x, do you want a PR to rmove deprecation warning? (or maybe you can just cherry-pick 9306d3e )

It already should be at 9.x. I released in 9.8.6.5.

> For 10.x, I think this issue here is we need to check whether the runtime supports the feature set we need.

This issue is was by my mistake of put 10.x code to the 9.x branch.

In 10.x we do not need to support old Node.js 6. I added to ChacnheLog that we do not support it anymore.

But we can print a nice error message if you want to add an extra checks.

**Comment by albb0920** [comment]
Thanks! I think I'll try to make the error nicer after I work on #179
