### ISSUE TITLE
Remove spec files from gem

### ISSUE THREAD

**Issue by ai** [ai/autoprefixer-rails#179]
We can make the gem file much smaller by removing `_spec.rb` files

**Comment by ai** [comment]
Another question: is it a good practice to remove spec files or Ruby developers will expect it?

**Comment by albb0920** [comment]
https://github.com/rubygems/rubygems/blob/master/bundler/lib/bundler/templates/newgem/newgem.gemspec.tt

At lease the bundler's new gem template excludes them, I think excluding tests are the norm.

**Comment by ai** [comment]
I agree. Tests can be useful in small gems to explain how gem works (as a part of docs). For Autoprefixer Rails tests will not help a developer. They just spend SSD size.
