### ISSUE TITLE
Node 12 installed but getting Autoprefixer doesn’t support Node v8.10.0. Update it.

### ISSUE THREAD

**Issue by samstickland** [ai/autoprefixer-rails#189]
Firstly, thanks for continuing to maintain this gem! Sorry to be here with a issue :(

I just started receiving this message recently on our Codeship builds, which is very odd, because we didn't change anything that I know of. 

```
$ node -v
v12.16.3
$ ruby -v
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]
```

Not sure where it's finding 8.10.0 from - any ideas how I can hunt this down? We aren't using Ruby Racer.

**Comment by samstickland** [comment]
Ah, I found some more information. The above was with 10.0.0.2, but regressing to 9.8.6.5 'fixes' the issue.

**Comment by samstickland** [comment]
And I should add that Codeship run Ubuntu AFAIK. The node version detection was working correctly on my Mac.

**Comment by mountaindog** [comment]
I ran into the same issue. Pushed an update to Codeship and it failed with the same error message. The only changes were a bundle update, that updated Autoprefixer to 10.x  Yes, downgrading / rolling-back to 9.8.6.5 temporarily "fixes" the issue.

**Comment by joesiewert** [comment]
Maybe related to the changes in https://github.com/ai/autoprefixer-rails/pull/182?

**Comment by albb0920** [comment]
There’s definitely 8.10.0 installed somewhere in the image, probably system package.

v9 to v10 is a major version change, which drops EOL node versions.

**Comment by mountaindog** [comment]
FYI - I set up Travis CI and it returned the same error msg - Autoprefixer doesn’t support Node v8.10.0. Let me know if you would like more details on the setup.

**Comment by albb0920** [comment]
For Codeship, this is due to the current released version of execjs prefers `nodejs` command if exists over `node`, nvm only handles `node` while Ubuntu packages nodejs as `nodejs`.

Adding this line in your setup commands should fix this.
```sh
ln -s $(which node) ~/bin/nodejs
```

**Comment by albb0920** [comment]
For Travis CI, something like this should work:

```yaml
language: ruby
rvm:
  - 2.6.6
before_install:
  - gem install bundler -v 2.1.4
  - nvm install node
  - bundle
script:
  - bin/rails assets:precompile
```

I'm closing this as this is more related to the execjs gem and individual environments.
Feel free to further discuss this issue. ;)

**Comment by samstickland** [comment]
@albb0920 Thanks!
