### ISSUE TITLE
TypeError: fileURL.repalce is not a function (ExecJS::ProgramError)

### ISSUE THREAD

**Issue by bunnymatic** [ai/autoprefixer-rails#192]
I noticed you have a fix for this.  

https://github.com/ai/autoprefixer-rails/commit/0fc26b5286264521e3fb4929abd9dec105c15a78

I wonder if you have plans to release a new version?  I'd love to use your gem and get around the v9 deprecation warnings.

**Comment by albb0920** [comment]
Will release a new version today, sorry for this

**Comment by albb0920** [comment]
Released as 10.0.1.1
