### ISSUE TITLE
ExecJS::ProgramError: TypeError: existsSync is not a function

### ISSUE THREAD

**Issue by pollinoco** [ai/autoprefixer-rails#193]
I have this issue with version 10.0.1.1

ExecJS::ProgramError: TypeError: existsSync is not a function 
PreviousMap.loadFile ((execjs):9628:11)
       PreviousMap.loadMap ((execjs):9667:21)
       new PreviousMap ((execjs):9562:23)
       new Input ((execjs):9721:17)
       parse$3 ((execjs):9830:19)
       new LazyResult$1 ((execjs):9960:18)
       Processor$1.process ((execjs):10369:14)
       process ((execjs):22757:61)
       eval (eval at <anonymous> ((execjs):22778:8), <anonymous>:1:23)
       (execjs):22778:8

**Comment by morgoth** [comment]
I have the same problem. Freezing to `10.0.1.0` for now (which is a working fine version)

**Comment by albb0920** [comment]
Can any of you share your execjs runtime information? Thanks!
(node or miniracer & version)

**Comment by morgoth** [comment]
```
 node -v
v12.19.0
```

**Comment by BenoitMC** [comment]
Same problem.

```
node -v
v14.12.0
```

**Comment by albb0920** [comment]
This happens when input css contains source map annotation, which postcss will try to load for chaining.

Execjs runtimes are not able to read files, the browser build of postcss didn't handle this .

I'll release a patch very soon, thanks everyone for reporting this.
