### ISSUE TITLE
Support building with @rollup/plugin-node-resolve@^10.0.0

### ISSUE THREAD

**Issue by pravi** [ai/autoprefixer-rails#199]
I'm a maintainer of autoprefixer-rails in debian. I'd like to build autoprefixer-rails with a newer version of @rollup/plugin-node-resolve@^10.0.0 but the build currently fails with error.

Note: Debian ships yarn as yarnpkg command.

```
(debian-sid)pravi@ilvala2:~/forge/js-team/autoprefixer-rails-10.1.0.0/build$ yarnpkg upgrade @rollup/plugin-node-resolve@^10.0.0
yarn upgrade v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ @rollup/plugin-node-resolve@10.0.0
info All dependencies
└─ @rollup/plugin-node-resolve@10.0.0
Done in 3.75s.

$ yarnpkg run rollup -c
yarn run v1.22.10
$ /home/pravi/forge/js-team/autoprefixer-rails-10.1.0.0/build/node_modules/.bin/rollup -c

autoprefixer.js → ../vendor/autoprefixer.js...
[!] Error: Could not load process (imported by node_modules/postcss/lib/postcss.js): ENOENT: no such file or directory, open 'process'
Error: Could not load process (imported by node_modules/postcss/lib/postcss.js): ENOENT: no such file or directory, open 'process'

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

Originally reported in debian as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=977900

**Comment by pravi** [comment]
https://github.com/rollup/plugins/pull/588 seems to be the breaking change here

**Comment by albb0920** [comment]
Hi

Thanks for the report, I'll take a look at this. (Might take some time though)

Is there any particular reason you want to regenerate the bundled js for debian package?
We already ship it with our package without minimization.
https://github.com/ai/autoprefixer-rails/blob/master/vendor/autoprefixer.js

Since rollup's node-resolve plugin is only used for generating the bundled script, there's really no point of upgrading it if it ain't broke.

**Comment by pravi** [comment]
1. We want to include only actual source code in debian source package. All generated files should be generated using tools packaged in debian. So bundled autoprefixer.js should be built from its source.
2. We also try to keep only one version of a module in debian (in exceptional cases we allow multiple versions, but we try our best to avoid it). This is to reduce the number of versions we have to provide security support in a stable release. So ideal solution is to be able to build with @rollup/plugin-node-resolve 10. If we fail to fix the build with this version, we may be forced to include @rollup/plugin-node-resolve 9, which we want to avoid if possible.

**Comment by albb0920** [comment]
Upgraded to latest version, works fine without any code change.
