### ISSUE TITLE
Autoprefixer doesn’t support Node v13.14.0. Update it.

### ISSUE THREAD

**Issue by macnick** [ai/autoprefixer-rails#201]
Mac OS 10.13.6 High Sierra
node  v13.14.0
ruby 2.6.4
rails 6.0.3.5

```
  Rendered users/index.html.erb within layouts/application (Duration: 23.1ms | Allocations: 7469)
  Rendered layouts/_bootstrap.html.erb (Duration: 0.4ms | Allocations: 83)
  Rendered layouts/_default.html.erb (Duration: 2953.5ms | Allocations: 1967339)
Completed 500 Internal Server Error in 2990ms (ActiveRecord: 5.4ms | Allocations: 1978745)


  
ActionView::Template::Error (Autoprefixer doesn’t support Node v13.14.0. Update it.):
    2: <%= csrf_meta_tags %>
    3: <%= csp_meta_tag %>
    4: 
    5: <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    6: <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    7: 
    8: <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
app/views/layouts/_default.html.erb:5
app/views/layouts/application.html.erb:6
```

Problem appears on line 5

**Comment by ai** [comment]
Node.js 13 has no security updates. Update to Node.js 14 as soon as possible.

https://nodejs.org/en/about/releases/

**Comment by ai** [comment]
In hte future, avoid installing odd Node.js versions. They are for experiments, not for the production.

**Comment by macnick** [comment]
Sorry, I didn't know that. Thank you so much for your fast response.

**Comment by jaswinder97** [comment]
I already have node version managed by nvm and on system path it gives latest version:

> node -v
v14.15.3

Now, I want autoprefixer to use node version currently set via nvm.

**Comment by DamilolaAjayi** [comment]
> I already have node version managed by nvm and on system path it gives latest version:
> 
> > node -v
> > v14.15.3
> 
> Now, I want autoprefixer to use node version currently set via nvm.

Hi @jaswinder97 
It should. what are the issues you have with that?

**Comment by jasonperrone** [comment]
That's happening to me, too. I have nvm aliased default to 12.22.1. node -v from command line = 12.22.1. When I build I get this: Autoprefixer doesn’t support Node v8.10.0. Update it.

No idea where it's getting 8.10.0 from...

**Comment by DamilolaAjayi** [comment]
> That's happening to me, too. I have nvm aliased default to 12.22.1. node -v from command line = 12.22.1. When I build I get this: Autoprefixer doesn’t support Node v8.10.0. Update it.
> 
> No idea where it's getting 8.10.0 from...

Hi @jasonperrone, this should help you. https://stackoverflow.com/a/67384646/9089093
If you run this `/usr/bin/nodejs` in your console and it returns `v8.10.0`, it means you had leftover executable nodejs and that's what's causing this problem. 

Take it out by running `git rm -rf /usr/bin/nodejs` in your terminal. Also, upgrade to at least a nodejs v14

**Comment by jasonperrone** [comment]
Thanks, I forgot to mention that I fixed the problem by uninstalling nodejs. But I appreciate you responding.
