### ISSUE TITLE
Causes extremely slow CSS compilation on Apple Silicon

### ISSUE THREAD

**Issue by ykessler** [ai/autoprefixer-rails#207]
Just recently transferred a Rails project to a new 2020 M1 Macbook Pro, and spent a couple of days trying to figure out why CSS compilation was taking _much_ longer on the new machine (over 30 sec, compared to 5 sec on my old box). 

Turns out as soon as I commented out the autoprefixer-rails gem (10.2.5.1) compilation times dropped to nearly instantaneous. No idea why.

Sorry for the lack of detail, this thing just threw me for a loop and I just wanted to let you know. I can answer questions if you have any.

**Comment by albb0920** [comment]
Hi

* Which javascript runtime are you using? Can you try switching to another runtime? (EXECJS_RUNTIME=MiniRacer vs EXECJS_RUNTIME=Node)
* Can you try running autoprefixer directly against your CSS to see if this is a rails gem specific issue?

Thanks

**Comment by ykessler** [comment]
Just tried with MiniRacer and that resolved the issue! Any thoughts on why that might be?

I'll try running autoprefixer directly when I get a chance

**Comment by ykessler** [comment]
I was inadvertently running an older version of Node (v12.14.0). Installing latest Node version (v16.2.0) cleared up the issue entirely (as did using MiniRacer as an alternative runtime.). Sorry my dumb mistake.

**Comment by albb0920** [comment]
It is definitely helpful to know node 12 may cause degraded performance, thank you for reporting this.
