### ISSUE TITLE
Autoprefixer very slow

### ISSUE THREAD

**Issue by lesliev** [ai/autoprefixer-rails#214]
Running Autoprefixer during the deployment of our application takes more than 20 minutes. Is there anything we can do to speed it up? We are on Rails 5.2 and autoprefixer-rails-9.7.4 - we could upgrade it but I don't see anything in Changelog that indicates speed improvements.

Our `.browserslistrc` is:
```
defaults
IE 11
```
...which produces:
```
and_chr 92
and_ff 90
and_qq 10.4
and_uc 12.12
android 92
baidu 7.12
chrome 92
chrome 91
chrome 90
edge 92
edge 91
firefox 91
firefox 90
firefox 89
firefox 78
ie 11
ios_saf 14.5-14.7
ios_saf 14.0-14.4
kaios 2.5
op_mini all
op_mob 64
opera 78
opera 77
safari 14.1
safari 14
safari 13.1
samsung 14.0
samsung 13.0
```

I wanted to try timing it with fewer browers in this list but I don't see how to execute Autoprefixer manually on local. Running `bundle exec rake assets:precompile RAILS_ENV=production` doesn't seem to do it.

**Comment by albb0920** [comment]
Can you test how much time it cost to precompile without autoprefixer?
Thanks

2021年8月25日(水) 11:04 Leslie Viljoen ***@***.***>:

**Comment by lesliev** [comment]
OK, I will report back when I've done that.

**Comment by albb0920** [comment]
Close this issue for inactivity, please reopen if needed.
