### ISSUE TITLE
gem causing problems after assets precompilation

### ISSUE THREAD

**Issue by cromega** [ai/autoprefixer-rails#227]
I'm trying to build a docker image of our app with precompiled assets, without a nodejs runtime in the final container.

I can confirm that running `assets:precompile` adds the CSS prefixes are in the generatd CSS.

After starting the app without a JS engine and with `EXECJS_RUNTIME` set to `Disabled`, the app raises an error right on the first request and the error is coming from this gem, it's complaining about the disabled JS runtime. It looks like the gem wants to process the assets even though everything has already been precompiled.

Rails: 7.0.8.4
Sprockets: 4.2.1

**Comment by albb0920** [comment]
Can you confirm if your app is running in rails env `production`?
I believe rails shouldn’t attempt to compile assets in prod.
I’ll also try to verify this on my end

**Comment by cromega** [comment]
Yep, I'm building images with production rails settings

**Comment by cromega** [comment]
tbh, having thought about it some more, I don't think that the problem is specifically in this gem, it's probably down to sprockets.

**Comment by albb0920** [comment]
I can't reproduce this issue with `config.assets.compile = false`  (default for `production`) on rails 7.1
If possible, please provide a minimal rails project that could reproduce this issue, thanks!

**Comment by cromega** [comment]
@albb0920 I'm pretty sure the weird behaviour was caused by a mix of things, I'm closing the issue for now.
