### ISSUE TITLE
Autoprefixer doesnt work on Heroku 

### ISSUE THREAD

**Issue by izelnakri** [ai/autoprefixer-rails#26]
Autoprefixer works well locally however when I deploy it to heroku apparently it doesnt work at the assets:precompile phase.
- Gem is not in any namespace
- Assets are precompiled at deployment
- config.assets.compile = false
- Rails v4.1.2 , Ruby v2.1.2

**Comment by dwbutler** [comment]
We had this same issue. We fixed it by bumping the `config.assets.version` in `config/application.rb`.

**Comment by moussasarr** [comment]
@dwbutler , I am having a problem with your groupify gem. Here is my problem http://stackoverflow.com/questions/29112512/rails-groupify-gem
Can you please also help me with the groupify implementation :http://stackoverflow.com/questions/30042320/what-is-a-good-way-to-add-group-functionality-with-rails?noredirect=1#comment48202047_30042320
