### ISSUE TITLE
Encoding::Undefined Conversion Error

### ISSUE THREAD

**Issue by mfurlend** [ai/autoprefixer-rails#31]
I attempted to invoke autoprefixer through compass as instructed, but when it runs I get this error:

```
cmd.exe /D /C C:/Ruby193/bin/compass.bat compile C:\E\gitstore\public\sass\model_explorer.scss
    write styles/model_explorer.css
Encoding::UndefinedConversionError on line ["22"] of C: "\x9D" to UTF-8 in conversion from Windows-1252 to UTF-8
Run with --trace to see the full backtrace

Process finished with exit code 1
```

Here is my config.rb file:

``` ruby
require 'bootstrap-sass'
require 'compass/import-once/activate'
require 'autoprefixer-rails'
# Require any additional compass plugins here.


# Set this to the root of your project when deployed:
http_path = "/"
css_dir = "styles"
sass_dir = "sass"
images_dir = "images"
javascripts_dir = "js"

# You can select your preferred output style here (can be overridden via the command line):
# output_style = :expanded or :nested or :compact or :compressed

# To enable relative paths to assets via compass helper functions. Uncomment:
# relative_assets = true

# To disable debugging comments that display the original location of your selectors. Uncomment:
# line_comments = false

preferred_syntax = :scss
on_stylesheet_saved do |file|
  css = File.read(file.gsub(/\\/,'/'))
  File.open(file, 'w') do |io|
        io << AutoprefixerRails.process(css, safe:true)
  end
end
```

I don't know if it makes a difference, but I am invoking compass through at PHPStorm File Watcher.

**Comment by henrahmagix** [comment]
I came across this problem when I installed Git for Windows and asked it to checkout as Unix-style line-endings. Before that I had asked for Windows-style checkout, Unix-style commit (the first option, default/recommended) and had no trouble with Compass compilation. Upon reinstalling Git with the first option checked, the problem went away after moving to another branch and back.

My error came from Sass, but it was the exactly the same:
>"\x9D" to UTF-8 in conversion from Windows-1252 to UTF-8

**Comment by ai** [comment]
@henrahmagix Sorry, I can’t fix Windows errors, because I have no Windows machine. But I am totally open for PR :).

**Comment by henrahmagix** [comment]
Oh I don't have a solution for this repo, I just thought I'd post my solution for the problem as it was caused by Git, since it's fairly common that the source of a project will have been committed Unix-style. Obviously not everyone uses Git, but if they do then the above will hopefully work.

**Comment by domschmidt** [comment]
Would be nice if someone could provide a fix for this issue :-)
