### ISSUE TITLE
Doesn't work on SCSS files.

### ISSUE THREAD

**Issue by slavingia** [ai/autoprefixer-rails#43]
Works great on SASS files but doesn't seem to run on SCSS files.

**Comment by weavermedia** [comment]
@slavingia did you solve this? I'm having the same issue.

**Comment by simkessy** [comment]
I tried that but it's not working either

```
.process-container {
  .fa {
    font-size: 100px;
    background: $gradient;
    background-clip: text;
    text-fill-color: transparent;
  }
}
```
I was hoping it would add vendor prefixes to `background-clip` and `text-fill-color` but it didn't. 

When I removed everything from application.scss and added the rules you put up, it worked for that.

**Comment by ai** [comment]
This properties do not need prefixes for default browsers set.
