### ISSUE TITLE
vendor prefix not added

### ISSUE THREAD

**Issue by stoplion** [ai/autoprefixer-rails#58]
Having trouble with this Gem:

//installing..
`gem "autoprefixer-rails"`

//bundle install and cache clear
`rake tmp:clear`

```
//in Sass file
body
   box-sizing: border-box
```
//outputs
box-sizing: border-box;

No `-moz-box-sizing`, webkit, etc.

I'm I missing something with the directions?
I am using Rails 4 with Compass and Sass.

**Comment by ai** [comment]
All current browsers works with `box-sizing` without prefixes ;) http://caniuse.com/#search=box-sizing

**Comment by stoplion** [comment]
I guess should rephrase my question. 

`rake autoprefixer:info | grep border-box` verifies that by default `border-sizing` is not supported. 
We support FF 21. FF 21 is not a "current browser". This I know. Is there a way to add support for it? Thanks.

**Comment by ai** [comment]
Put `browserslist` config and write browsers requirements by [Browsersconfig docs](https://github.com/ai/browserslist). Like this:

```
> 1%
Last 2 versions
Firefox ESR
Opera 12.1
Firefox 21
```
