### ISSUE TITLE
Instructions for Windows Ruby install

### ISSUE THREAD

**Issue by boucains** [ai/autoprefixer-rails#59]
Please forgive a poor noob - I am brand new at using these tools.

For Ruby, the instructions say to use 'gem "autoprefixer-rails"', but on my system, at least, I had to use  'gem install "autoprefixer-rails"' instead.

Is it possible that this is an error in the github repository webpage for Autoprefixer, of did I just make a mistake?

Thanks for providing such a useful tool!!

**Comment by ai** [comment]
`gem "autoprefixer-rails"` is not a CLI command. It is a line for [Bundler’s](http://bundler.io/) `Gemfile`.

**Comment by boucains** [comment]
спасибо! Thank you for teaching me - and for not biting my head off.
