### ISSUE TITLE
Failure to Convert readme.md

### ISSUE THREAD

**Issue by boucains** [ai/autoprefixer-rails#60]
Please forgive a poor noob - I am brand new at using these tools.

When installing autoprefixer with Ruby, I encountered two error messages related to the readme.md file. Please see the output below for the actual error:

C:\Users\John>gem install "autoprefixer-rails"
Fetching: execjs-2.4.0.gem (100%)
Fetching: autoprefixer-rails-5.1.7.1.gem (100%)
Successfully installed execjs-2.4.0
Successfully installed autoprefixer-rails-5.1.7.1
2 gems installed
Installing ri documentation for execjs-2.4.0...
Installing ri documentation for autoprefixer-rails-5.1.7.1...
unable to convert U+2019 from UTF-8 to IBM437 for README.md, skipping
Installing RDoc documentation for execjs-2.4.0...
Installing RDoc documentation for autoprefixer-rails-5.1.7.1...
unable to convert U+2019 from UTF-8 to IBM437 for README.md, skipping.

If this wasn't a stupid mistake on my part, maybe the error could be fixed, or the error message changed if the error is benign?

**Comment by ai** [comment]
Try to use `gem install "autoprefixer-rails" --no-rdoc`

**Comment by ai** [comment]
BTW, why you need to install Autoprefixer Rails? Why not node’s Autoprefixer?

**Comment by ai** [comment]
And Ruby on Windows is really bad idea :). You should install Linux :).
