### ISSUE TITLE
CSS "appearance" property not prefixed

### ISSUE THREAD

**Issue by AnthonyBobsin** [ai/autoprefixer-rails#62]
When attempting to set "appearance: none" on a checkbox, it should be setting prefixes for moz and webkit with the versions I'm supporting, but neither show. I did notice that IE doesn't support appearance at all, could this be the case of why prefixes weren't included?

**Comment by ai** [comment]
https://github.com/postcss/autoprefixer#why-doesnt-autoprefixer-support-appearance

But `appearance` will works in 5.2.

**Comment by ai** [comment]
BTW, it could not be a issue of Rails port. You should create this kind of issue in main Autoprefixer repository.

**Comment by AnthonyBobsin** [comment]
Oh wow, I apologize, I completely missed that in the README. Sounds good, I will remember that for next time. Thank you for being so understanding, and for creating an excellent gem.
