### ISSUE TITLE
Including autoprefixer-rails inside another gem

### ISSUE THREAD

**Issue by jasonblalock** [ai/autoprefixer-rails#63]
I use a style guide gem to wrap my assets that are used for multiple apps. I would like to just have autoprefixer-rails as a gemspec runtime dependency. When I add my style guide gem to my apps I can see autoprefixer-rails is in `bundle list` for the app. However autoprefixer doesn't ever autoprefix the assets when running the app. Is there any way to get that to work?

**Comment by ai** [comment]
Hm. It is a rare case, but seems like we should change the API to manually Autoprefixer enabling.

**Comment by ai** [comment]
Right now Autoprefixer will be added to Rails app if it find defined `Rails` constant.

**Comment by jasonblalock** [comment]
Thanks for the fast response. Could you clarify your last comment?

**Comment by ai** [comment]
I hope code will say it more clear than my English :D

https://github.com/ai/autoprefixer-rails/blob/master/lib/autoprefixer-rails.rb#L31
https://github.com/ai/autoprefixer-rails/blob/master/lib/autoprefixer-rails/railtie.rb#L15

**Comment by jasonblalock** [comment]
Thanks that was helpful. Just requiring autoprefixer-rails and autoprefixer-rails/railtie in my style guide gem seems to have gotten it running. The remaining issue is that it won't load the `browserslist` from the style guide. It looks like you have `Autoprefixer.process` which has an option `:from` that I could specify a different location for the config file when it's called in your railtie, but I don't think there's a way to pass a path into the railtie call.

**Comment by ai** [comment]
Just set a `browsers` option and Autoprefixer will not use `browserslist` config.

**Comment by jasonblalock** [comment]
Sorry how would I set a `browsers` option? I could copy code from your railtie and modify it in my style guide's railtie that uses the `browsers` option if that's what you mean. Or is there an easier way?

**Comment by ai** [comment]
What are you doing exactly. I didn’t understand your case.
