### ISSUE TITLE
Prefix -webkit-box comes after -webkit-flex

### ISSUE THREAD

**Issue by fredericlefeurmou** [ai/autoprefixer-rails#65]
The library angular-material already includes flex prefixes, so autoprefixer adds -webkit-box after -webkit-flex and breaks the layout on safari.

```
[layout] {
    box-sizing: border-box;
    display: -webkit-flex;
    display: -moz-flex;
    display: -ms-flexbox;
    display: -webkit-box;
    display: flex;
}
```

Is there any workaround?

**Comment by ai** [comment]
@fredericlefeurmou just clean CSS from prefixes and then add it again. Like:

```js
autoprefixer({ browsers: [] }).process(css, function (clean) {
    autoprefixer().process(clean.css, function (correct) {
    });
});
```

**Comment by alepee** [comment]
Hello and thanks @ai for the answer, same problem here with angular material, how would you apply it on sprockets pre-compile when deploying? I would like to keep it in the backend to serve correctly pre-compiled files and do not process them again on the fly.

**Comment by endenis** [comment]
We solved it by overriding angular-material's stylesheet in our own css file with using `/* autoprefixer: off */`.
A bit dirty but works.
