### ISSUE TITLE
Disable warnings

### ISSUE THREAD

**Issue by rnsloan** [ai/autoprefixer-rails#66]
Is it possible to disable warnings? Project i am working on has warnings coming from a vendor file and I would prefer not to have to fork the plugin in-order to upgrade autoprefixer and annoy the team with constant warnings.

Thanks

**Comment by ai** [comment]
You report in different project, becuase this task is irrelevant to Ruby integration. Can you open issue in main Autoprefixer repo?

**Comment by liorbrauer** [comment]
@ai I think this issue can be addressed on this project as well, no? I see there is code in `sprockets.rb`:

```ruby
result.warnings.each do |warning|
  $stderr.puts "autoprefixer: #{ warning }"
end
```

It would be useful to have an option to disable it, it can really overflow the log with warnings on some projects.

Thanks!

**Comment by ai** [comment]
@liorbrauer most of this warnings are really critical. So I am not big fan of disabling it. I will agree with it only if you will show me use case, when warning is not relevant and should not be fixed.

**Comment by liorbrauer** [comment]
@ai Well, one use case we have is a vendor file we depend on and cannot directly change that has the old `background-image: linear-gradient()` syntax (`left` instead of: `to right`).

**Comment by ai** [comment]
So this vendor file styles will not be visible in your clients browser. Mozilla ignores gradients without `to `. You should create a issue and ping file author every week, it is dangerous issue.

**Comment by ai** [comment]
Also you could write a Sprockets plugin to fix `left` to `to right` on the flight.

**Comment by liorbrauer** [comment]
@ai Alright, thank you for you feedback. I've decided to drop the offending dependency.

**Comment by ai** [comment]
@liorbrauer good choice :+1:
