### ISSUE TITLE
Hooking up `browserslist` could be easier

### ISSUE THREAD

**Issue by samjewell** [ai/autoprefixer-rails#67]
I struggled for an hour or two trying to hook up the browserslist config.

Can I suggest the following improvements to the readme?

1. Make it clearer that the file should be at `app/browserslist`, rather than just `browserslist` in the root folder of the project

2. Make it clear that every time you change the contents of browserslist, you'll have to clear the rails cache (`rake tmp:clear`) to see the new browser prefixes in your browser.

If you'll accept these changes, but you want me to make the PR then let me know - I can probably get round to it sooner or later (I'm not the fasters though - I've just 1 year in software development)

**Comment by ai** [comment]
Yeap, we should make it cleaner.

But `browserslist` should work from root. It works for any dirs and files inside current dir.

**Comment by samjewell** [comment]
Yes, just tried it, and yeah it does work from root. Maybe just number 2 above then?

**Comment by ai** [comment]
Does this code is OK? https://github.com/ai/autoprefixer-rails/blob/master/lib/autoprefixer-rails/processor.rb#L86

**Comment by samjewell** [comment]
Yeah that bit is fine - it's finding the browserslist config no probs now
