### ISSUE TITLE
Ability to disable autoprefixer

### ISSUE THREAD

**Issue by romansklenar** [ai/autoprefixer-rails#68]
Hello, is there a way how I can disable autoprefixer?

__Example:__ I don't need autoprefixer to recompile stylesheets when I want to quickly write an integration test and sometimes it's anoying to wait for 2 minutes for test result.
For this use case it'd be nice if I could disable autoprefixer in certain environments or in single test run using some ENV variable.

Thanks for you ideas and opinions.

**Comment by ai** [comment]
Just remove Autoprefixer postprocessor from Assets Pipeline. I will add code example, when I come back to home.

**Comment by ai** [comment]
Done 0190dd5

**Comment by romansklenar** [comment]
Thanks!

**Comment by connorshea** [comment]
I tried adding this to my `development.rb` environment file, but it doesn't disable Autoprefixer even after running `rake tmp:clear`:

```ruby
Rails.application.configure do
  config.assets.unregister_postprocessor('text/css', :autoprefixer)
end
```

Any idea how to do get this working?

**Comment by ai** [comment]
@connorshea maake sure that your run it after Autoprefixer was initialized

**Comment by connorshea** [comment]
I'm not initializing it manually anywhere, it's seemed to have added itself when I added the gem, as far as I can tell?

**Comment by ai** [comment]
Yeap, but seems like you disable it before it was enabled ;).

**Comment by ai** [comment]
Look to Rails’s `initializer`

**Comment by connorshea** [comment]
@ai I'm not sure I follow? There's no autoprefixer initializer in the initializers folder.
