### ISSUE TITLE
:in `<main>': undefined local variable or method `css' for main:Object (NameError)

### ISSUE THREAD

**Issue by spagu** [ai/autoprefixer-rails#70]
Used your very easy code and getting this:
test.rb:4:in `<main>': undefined local variable or method `css' for main:Object (NameError)

how to fix ?

**Comment by ai** [comment]
I can find anything by this tiny information.

1. Full stack trace.
2. What OS you use.
3. Do you use it in Rails?
4. What JS runtime you use for ExecJS
