### ISSUE TITLE
add required_ruby_version to gemspec for 6.0 release

### ISSUE THREAD

**Issue by atambo** [ai/autoprefixer-rails#75]
So now that 6.0 is incompatible with ruby 1.9 the required_ruby_version constraint should be added to the gemspec so that when people bundle update they wont get an incompatible version of the gem.

See:
http://guides.rubygems.org/specification-reference/#required_ruby_version=

**Comment by ai** [comment]
Do you want to send PR?

**Comment by atambo** [comment]
Pull request made: https://github.com/ai/autoprefixer-rails/pull/76

**Comment by ai** [comment]
Thanks. I will release it in next version.
