### ISSUE TITLE
6.1.2 no longer compatible with ruby 1.9

### ISSUE THREAD

**Issue by hugocorbucci** [ai/autoprefixer-rails#77]
Is this really necessary? If so, shouldn't it be a bigger bump than a patch level version?

6.1.1 was compatible with ruby 1.9. Removing that compatibility seems like it deserves a major version change or, at least, a minor version change. No?

**Comment by hugocorbucci** [comment]
I see that #75 says 6.0 shouldn't have been compatible with ruby 1.9 anymore. I was using it just fine in a few projects so I didn't even realize it. Seems weird at a patch level release anyway. But, you know better...

**Comment by ai** [comment]
1.9 support and Rails 3 support [was removed](https://github.com/ai/autoprefixer-rails/blob/master/CHANGELOG.md#60-eureka) in 6.0.

In 6.1.2 we just fix gemspec.

**Comment by ai** [comment]
Why you can’t update to Ruby 2.2?

**Comment by hugocorbucci** [comment]
We can.. it's just a long needed fix on our puppet config to allow for rbenv or rvm or get us ready for phoenix all the way.
It was just surprising since I was using ruby 1.9 successfully with 6.1.1 and a patch level upgrade broke my build. That's fine. I'll handle it.
