### ISSUE TITLE
autoprefixer-rails requires Ruby version >= 2.0.

### ISSUE THREAD

**Issue by DonIvanCorleone** [ai/autoprefixer-rails#80]
Hi there,

I recently tried to create a new project using rails-composer and jRuby 1.7.23 and stumbled up on the above shown error (autoprefixer-rails requires Ruby version >= 2.0.)

Any ideas how to circumvent this problem?

Many thanks
Ivan

**Comment by ai** [comment]
Update JRuby? :-)
