### ISSUE TITLE
Using plugins

### ISSUE THREAD

**Issue by brain-geek** [ai/autoprefixer-rails#82]
Right now I have a html created with postcss-mixins and postcss-nested, which I want to use in my Rails project.

I've looked through project code and looks like autoprefixer.js includes full JS project, and that file can be changed only via forking repo. 

Is there a way I can use postcss plugins this using upstream version?

**Comment by ai** [comment]
Sorry, right now there is no way to use PostCSS in Rails Assets Pipeline. You should move to webpack or Gulp. See https://github.com/mipearson/webpack-rails

Main problem is that ExecJS do not support CommonJS with `require()`. But anyway right now Sprockets seems like dead project. No future, not many other tools. This is why I really recommend you to move to Gulp and webpack.

**Comment by brain-geek** [comment]
Thanks for the help.
