### ISSUE TITLE
undefined method `root' for nil:NilClass

### ISSUE THREAD

**Issue by lencioni** [ai/autoprefixer-rails#84]
I'm working on setting up autoprefixer-rails, and it seems to work alright in development. However, when I run the rake task to precompile assets, I get the following stacktrace:

```
undefined method `root' for nil:NilClass
/home/vagrant/.gem/gems/autoprefixer-rails-5.2.1.3/lib/autoprefixer-rails/railtie.rb:10:in `block in <class:Railtie>'
/home/vagrant/.gem/gems/railties-3.0.20.11lts.1/lib/rails/railtie.rb:185:in `call'
/home/vagrant/.gem/gems/railties-3.0.20.11lts.1/lib/rails/railtie.rb:185:in `each'
/home/vagrant/.gem/gems/railties-3.0.20.11lts.1/lib/rails/railtie.rb:185:in `load_tasks'
/home/vagrant/.gem/gems/railties-3.0.20.11lts.1/lib/rails/application.rb:140:in `block in load_tasks'
/home/vagrant/.gem/gems/railties-3.0.20.11lts.1/lib/rails/application/railties.rb:11:in `each'
/home/vagrant/.gem/gems/railties-3.0.20.11lts.1/lib/rails/application/railties.rb:11:in `all'
/home/vagrant/.gem/gems/railties-3.0.20.11lts.1/lib/rails/application.rb:140:in `load_tasks'
/home/vagrant/.gem/gems/railties-3.0.20.11lts.1/lib/rails/application.rb:77:in `method_missing'
/home/vagrant/repos/project/Rakefile:12:in `<top (required)>'
/var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/rake_module.rb:25:in `load'
/var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/rake_module.rb:25:in `load_rakefile'
/var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:501:in `raw_load_rakefile'
/var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:82:in `block in load_rakefile'
/var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:81:in `load_rakefile'
/var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:65:in `block in run'
/var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/var/lib/gems/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/home/vagrant/.gem/bin/rake:23:in `load'
/home/vagrant/.gem/bin/rake:23:in `<main>'
```

This is in an aging project that is still using Ruby 1.9.3 and Rails 3.0, so I am seeing this on autoprefixer-rails 5.2.1.3. I've dug into the railtie code some, but I'm not really sure how this is supposed to work. Do you have any thoughts on what I might be doing wrong here?

**Comment by lencioni** [comment]
This is the code in autoprefixer-rails that is erroring:

```rb
rake_tasks do |app|
  require 'rake/autoprefixer_tasks'
  Rake::AutoprefixerTasks.new( config(app.root)[0] )
end
```

And this is the code one level up the stacktrace:

```rb
self.class.rake_tasks.each(&:call)
```

which doesn't pass any arguments to the `rake_tasks` blocks.

**Comment by ai** [comment]
You should update Ruby. Sorry, but main idea of Autoprefixer is to use *latest* version. It is really important.

Why you can’t update Ruby to at least 2.0?

**Comment by lencioni** [comment]
I did some digging and it looks like this won't work under Rails 3.0. Here's the relevant bit of Rails 3.0 code: https://github.com/rails/rails/blob/b875be03b50029e94244945f072a6cbbff2e1c24/railties/lib/rails/railtie.rb#L185

Rails 3.1 changes this to https://github.com/rails/rails/blob/a7dd0bb151d925a7e3cd0aec8f61746729949985/railties/lib/rails/railtie.rb#L188

> Why you can’t update Ruby to at least 2.0?

I'd like to do this, but I think it will require considerable effort for this project. I believe that there are people on my team that are working on it.
