### ISSUE TITLE
Sprockets 4 support

### ISSUE THREAD

**Issue by ai** [ai/autoprefixer-rails#88]
Because `sass-rails` doesn’t support Sprockets 4, I can’t test them with new AutoprefixerRails.

@glebm can you check code? https://github.com/ai/autoprefixer-rails/blob/master/lib/autoprefixer-rails/sprockets.rb#L35-L54

1. It uses old way to add Autoprefixer for Sprockets 2-3 to keep old `unregister` code.
2. it now has `AutoprefixerRails.uninstall` method to hide uninstall logic.
3. it uses `register_bundle_processor` to work faster in Sprockets 4.

**Comment by schneems** [comment]
Awesome, I'm out with the family this weekend I can take a closer look this week

**Comment by glebm** [comment]
I think sass-rails master supports Sprockets 4, so we can test with that.

**Comment by ai** [comment]
OK. Sprockets 4 and Rails 5 was tested.

**Comment by ai** [comment]
Released in 6.3.3.1
