### ISSUE TITLE
Please use better versioning

### ISSUE THREAD

**Issue by ckruse** [ai/autoprefixer-rails#91]
Today I did a `bundle update`, checked the updated gems and accepted the version upgrade of autoprefixer-rails to 6.3.6.1 - a minor-minor update, shouldn't change anything important and only a bug report was mentioned.

Half an hour after the push to production a user with an old iPhone 4s said that his stylesheets were horribly broken. After investigating for about an hour I remembered the update and checked commit history of autoprefixer-rails - you updated the caniuse data as well and it seems that this dropped some flexbox prefixes.

Could you please do a less minor version change if your update contains things like this? With a 6.4 or a 6.3.7 I would have looked closer at the changes. Since these are breaking changes a 6.4 would've been appropriate, IMHO...

**Comment by ai** [comment]
@ckruse your `browsersconfig` contains `last 2 version` (or was a default value). Last 2 versions of iOS is 9.3 and 9.2. Every Autoprefixer Rails release contain new Can I Use data. So `6.3.6.1` contains new 9.3 iOS release, It removed iOS 8.4 from `last 2 version`.

If you need to support iPhone 4s, please add `iOS 8.4` to your `browsersconfig`. But you had a `last 2 version` and update was totally correct and safe for your browsers set.
