### ISSUE TITLE
Update from 6.3.6 to 6.3.6.1 version break tests on PhantomJS

### ISSUE THREAD

**Issue by le0pard** [ai/autoprefixer-rails#92]
Hello.

I trying to update project with autoprefixer-rails from 6.3.6 to 6.3.6.1 version. But after this was broken tests on PhantomJS:

```
Failure/Error: find('li.email span.title', text: message.subject ).click
     
     Capybara::Poltergeist::MouseEventFailed:
       Firing a click at co-ordinates [53, 108] failed. Poltergeist detected another element with CSS selector 'html.js.flexbox.flexboxlegacy.canvas.canvastext.no-webgl.touch.no-geolocation.postmessage.websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.cssreflections.csstransforms.no-csstransforms3d.csstransitions.fontface.generatedcontent.no-video.no-audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths body div#falconApp.wrapper div#main.main div.page_body.page-body.inbox-messages.row' at this position. It may be overlapping the element you are trying to interact with. If you don't care about overlapping elements, try using node.trigger('click').
```

And many similar problems. After rollback to 6.3.6 tests pass again. Current env:

* rails 4.2.6
* phantomjs 2.1.1
* poltergeist 1.9.0
* rspec 3.4.0
* capybara 2.7.1
* sprockets 2.12.4
* sprockets-rails 2.3.3

browserlist

```
last 2 version
> 5%
Firefox ESR
Opera 12.1
```

We are using flexbox and maybe last changes influence on its in different way (phantomjs 2 support flexbox). On saved screenshot I see, what element disappear from block, where it should be.

With autoprefixer-rails 6.3.6.1:

![6 3 6 1](https://cloud.githubusercontent.com/assets/98444/15627603/2771ddf8-24f2-11e6-9b6a-773e7a3e3015.png)

With autoprefixer-rails 6.3.6:

![6 3 6](https://cloud.githubusercontent.com/assets/98444/15627605/2d42cfd0-24f2-11e6-991f-689f1a4f9e75.png)

Should I check something else to fix this issue? Thanks in advance.

**Comment by ai** [comment]
You need to put correct browsers list. `last 2 version` doesn’t hit your PhantomJS anymore (it has some old webkit kernel, so it will be something like `chrome 23`)

**Comment by ai** [comment]
`last 2 version` is dynamic requirement, so it will change during a time, because browsers release new versions ;)

**Comment by le0pard** [comment]
Ok, thanks. I was expected, what phantomjs 2.1.1 (it latest release of it) will fit this requirements. Thanks for help.

**Comment by psugihara** [comment]
@le0pard did `chrome 23` in your browserlist work? I also found this suggesting `safari >= 4`: https://github.com/ariya/phantomjs/issues/14365

**Comment by le0pard** [comment]
@psugihara yes, `Chrome 23` solved this problem.
