### ISSUE TITLE
It breaks bootstrap grid on render pdf

### ISSUE THREAD

**Issue by mduqueoviedo** [ai/autoprefixer-rails#95]
Hello there,

I am using autoprefixer in my app with no problem. However, I am generating a pdf with the wicked_pdf gem with default Bootstrap 3 styling and there the layout is broken. When using two columns of width 6 they cannot be in the same line, but they go to the next line. 

When I remove the gem from the app, everything works and pdf looks fine.

**Comment by ai** [comment]
Do you set correct `browsers` option? Most of PDF generators uses old webkit engine, so default browsers doesn’t match them.

**Comment by mduqueoviedo** [comment]
It makes sense. Which option is that then? I cannot see it anywhere in the documentation, I recommend you to add it.
