### ISSUE TITLE
Deprecation warning with Sprockets 3.7.0

### ISSUE THREAD

**Issue by benoitongit** [ai/autoprefixer-rails#98]
DEPRECATION WARNING: You are using the a deprecated processor interface #<Proc:0x007f84725183a0@/Users/Benoit/.rvm/gems/ruby-2.3.0/gems/autoprefixer-rails-6.3.7/lib/autoprefixer-rails/sprockets.rb:37>.
Please update your processor interface:
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from install at /Users/Benoit/.rvm/gems/ruby-2.3.0/gems/autoprefixer-rails-6.3.7/lib/autoprefixer-rails/sprockets.rb:37)

**Comment by ai** [comment]
https://github.com/ai/autoprefixer-rails/issues/96

**Comment by ai** [comment]
Released in 6.4.
