### ISSUE TITLE
Release 6.3.8

### ISSUE THREAD

**Issue by jcoyne** [ai/autoprefixer-rails#99]
@ai would you mind putting out a new release? Thank you.

**Comment by ai** [comment]
Sure, when I finish 6.4.0 in Autoprefixer.js.

Autoprefixer Rails versions is linked with Autoprefixer.js versions.

Just wait a week 😉. Warning is not a big deal.

**Comment by ai** [comment]
6.4 was released

**Comment by jcoyne** [comment]
:tada: :clap: Thank you.
